import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "IMDb Clone",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body>
          {/* Header */}
          <Header />

          {/* Navbar */}

          {/* SearchBox */}
          
          {children}
          
          </body>
      </html>
    </>
  );
}
